from generalScrapingMod.Scripts.uncc_event_collection import test_event_collect
from generalScrapingMod.Scripts.dining_availability import test_dining_scrape
from generalScrapingMod.Scripts.parking_availability import test_parking_run


test_parking_run()
test_dining_scrape()
test_event_collect()

